### ISSUE TITLE
Container test failed: File not found: edge_index_PPI_990_disjoint.npy

### ISSUE THREAD

**Issue by wilke** [JDACS4C-IMPROVE/DRPreter#4]
FileNotFoundError: [Errno 2] No such file or directory: '/candle_data_dir/data_processed/edge_index_PPI_990_disjoint.npy'

Steps:

```bash
git clone https://github.com/JDACS4C-IMPROVE/Singularity.git
cd Singularity
git checkout switch-to-improve-branch
singularity build --fakeroot build/DRPreter.sif definitions/DRPreter.def
singularity run --nv --bind `pwd`/tmp/:/candle_data_dir build/DRPreter.sif train.sh 7 /candle_data_dir --epochs 1
....
{'model_name': 'drpreter', 'device': 'cuda:0', 'batch_size': 128, 'learning_rate': 0.0001, 'epochs': 1, 'layer': 3, 'layer_drug': 3, 'hidden_dim': 8, 'dim_drug': 128, 'dim_drug_cell': 256, 'dropout_ratio': 0.1, 'patience': 100, 'string_edge': 990, 'edge': 'STRING', 'dataset': 'disjoint', 'trans': True, 'sim': False, 'train_bool': True, 'profiling': False, 'experiment_id': 'EXP000', 'run_id': 'RUN000', 'verbose': False, 'logfile': None, 'shuffle': False, 'ckpt_restart_mode': 'auto', 'ckpt_checksum': False, 'ckpt_skip_epochs': 0, 'ckpt_directory': './save', 'ckpt_save_best': True, 'ckpt_save_best_metric': 'val_loss', 'ckpt_save_weights_only': False, 'ckpt_save_interval': 0, 'ckpt_keep_mode': 'linear', 'ckpt_keep_limit': 1000000, 'seed': 42, 'data_type': <class 'numpy.float32'>, 'output_dir': '/homes/wilke/release/Singularity/Output/EXP000/RUN000', 'rng_seed': 7102, 'timeout': -1}
CANDLE_DATA_DIR: /candle_data_dir
Traceback (most recent call last):
  File "/usr/local/DRPreter/drpreter_baseline_pytorch.py", line 387, in <module>
    main()
  File "/usr/local/DRPreter/drpreter_baseline_pytorch.py", line 382, in main
    run(gParameters)
  File "/usr/local/DRPreter/drpreter_baseline_pytorch.py", line 345, in run
    scores = launch(args)
  File "/usr/local/DRPreter/drpreter_baseline_pytorch.py", line 188, in launch
    edge_index = np.load(
  File "/opt/conda/lib/python3.10/site-packages/numpy/lib/npyio.py", line 427, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/candle_data_dir/data_processed/edge_index_PPI_990_disjoint.npy'
```

**Comment by mcnaughtonadm** [comment]
I'm working to track down where this error is originating from.

After running `candle.get_file()` the data is saved by default to `/candle_data_dir`. as `/candle_data_dir/data_processed.tar.gz` and unpacked to `/candle_data_dir/data_processed`. In this directory there is a `edge_index_PPI_990_disjoint.npy` file so I'm not sure why it is unable to find this data.

The code itself looks for the path 
```
edge_index = np.load(
        candle_data_dir + f"/data_processed/edge_index_{edge_type}_{args.dataset}.npy"
    )
```
I'm further looking into where the download/unpacking is putting things. It may be doubling up and doing `/candle_data_dir/data_processed/data_processed/edge_index_PPI_990_disjoint.npy`

**Comment by mcnaughtonadm** [comment]
Following the above commands, I am unable to recreate this error. When running, the candle.get_file() returns the data saved to `/candle_data_dir/data_processed/` and `edge_index_PPI_990_disjoint.npy` is able to be found. It did uncover a slightly later error that I just corrected on `develop`  in df6c2af

```bash
git clone https://github.com/JDACS4C-IMPROVE/Singularity.git
cd Singularity
git checkout switch-to-improve-branch
singularity build --fakeroot build/DRPreter.sif definitions/DRPreter.def
singularity run --nv --bind `pwd`/tmp/:/candle_data_dir build/DRPreter.sif train.sh 0 /candle_data_dir --epochs 1
.......
{'model_name': 'drpreter', 'device': 'cuda:0', 'batch_size': 128, 'learning_rate': 0.0001, 'epochs': 1, 'layer': 3, 'layer_drug': 3, 'hidden_dim': 8, 'dim_drug': 128, 'dim_drug_cell': 256, 'dropout_ratio': 0.1, 'patience': 100, 'string_edge': 990, 'edge': 'STRING', 'dataset': 'disjoint', 'trans': True, 'sim': False, 'train_bool': True, 'profiling': False, 'experiment_id': 'EXP000', 'run_id': 'RUN000', 'verbose': False, 'logfile': None, 'shuffle': False, 'ckpt_restart_mode': 'auto', 'ckpt_checksum': False, 'ckpt_skip_epochs': 0, 'ckpt_directory': './save', 'ckpt_save_best': True, 'ckpt_save_best_metric': 'val_loss', 'ckpt_save_weights_only': False, 'ckpt_save_interval': 0, 'ckpt_keep_mode': 'linear', 'ckpt_keep_limit': 1000000, 'seed': 42, 'data_type': <class 'numpy.float32'>, 'output_dir': '/home/mcna892/Singularity/Output/EXP000/RUN000', 'rng_seed': 7102, 'timeout': -1}
CANDLE_DATA_DIR: /candle_data_dir
Downloading data from https://ftp.mcs.anl.gov/pub/candle/public/improve/model_curation_data/DRPreter/data_processed.tar.gz
15466496/15671553 [============================>.] - ETA: 0s
Unpacking file...
gene distribution: tensor([142,  94, 137, 294,  74, 155, 218,  79, 146, 190, 136, 293, 167,  73,
        232,  59, 239, 109, 104,  85, 126, 101, 221,  59,  56,  71,  44, 351,
        162,  96, 102,  41,  88, 102], dtype=torch.int32)
mean degree:2.5837279380111924
CUDA_VISIBLE_DEVICES: 0
total: 82833, train: 66266, val: 8283, test: 8284
===== Epoch 1 =====
Iteration: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 518/518 [00:14<00:00, 35.41it/s]
Train Loss:1.7811907529830933
Iteration: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 65/65 [00:01<00:00, 48.34it/s]
Validation mse: 2.1197032928466797
Iteration: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 65/65 [00:01<00:00, 47.95it/s]
Test mse: 2.1478495597839355
Iteration: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 518/518 [00:09<00:00, 55.21it/s]
Iteration: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 65/65 [00:01<00:00, 46.18it/s]
Iteration: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 65/65 [00:01<00:00, 48.22it/s]
-------- DRPreter -------
sim: False
##### Seed: 42 #####
		MSE	RMSE	MAE	PCC	SCC
Train result: 2.114000082015991	1.4539999961853027	1.1111	0.8898	0.8535
Val result: 2.1196999549865723	1.455899953842163	1.1098	0.8863	0.8487
Test result: 2.1477999687194824	1.4656000137329102	1.1223	0.8861	0.8492

IMPROVE_RESULT val_loss:	{'val_loss': 2.1196999549865723, 'mae': 1.1098, 'scc': 0.8487, 'pcc': 0.8863, 'rmse': 1.455899953842163}

Done.
```

**Comment by wilke** [comment]
@mcnaughtonadm  The error occurs if the data_processed directory exists in candle_data_dir but is empty. No download is triggered in this case.

Running with empty candle_data_dir:

```
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  [Previous line repeated 2 more times]
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 820, in _apply
    param_applied = fn(param)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1143, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

Did not include your patch. Rebuilding and testing.

**Comment by wilke** [comment]
Error occurs for GPU IDs > 0

**Comment by wilke** [comment]
The triggers for downloading default data can be improved but are not part of this issue. Closing this issue.
